export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const FETCH_MOVIELIST_FAILED = 'FETCH_MOVIELIST_FAILED';
export const GET_MORE_MOVIE_INFO = 'GET_MORE_MOVIE_INFO';
export const GET_MORE_MOVIE_CARDS = 'GET_MORE_MOVIE_CARDS';
export const GET_MORE_MOVIE_CARDS_ON_SCROLL = 'GET_MORE_MOVIE_CARDS_ON_SCROLL';