export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const FETCH_MOVIELIST_FAILED = 'FETCH_MOVIELIST_FAILED';
export const GET_MORE_MOVIE_INFO = 'GET_MORE_MOVIE_INFO';
export const GET_MORE_MOVIE_CARDS = 'GET_MORE_MOVIE_CARDS';
export const SET_TVSHOW_LIST = 'SET_TVSHOW_LIST';
export const GET_MORE_TVSHOW_INFO = 'GET_MORE_TVSHOW_INFO';
export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE';
export const FILTER_MOVIE_DATA = "FILTER_MOVIE_DATA";
export const GET_TRAILER = "GET_TRAILER";
export const SET_MOVIE = "SET_MOVIE";
export const SET_TRAILER = "SET_TRAILER";
export const CLOSE_TRAILER = "CLOSE_TRAILER";
export const SET_ACTOR_DETAILS = "SET_ACTOR_DETAILS"

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';