export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const FETCH_MOVIELIST_FAILED = 'FETCH_MOVIELIST_FAILED';
export const GET_MORE_MOVIE_INFO = 'GET_MORE_MOVIE_INFO';
export const GET_MORE_MOVIE_CARDS = 'GET_MORE_MOVIE_CARDS';
export const SET_TVSHOW_LIST = 'SET_TVSHOW_LIST';
export const GET_MORE_TVSHOW_INFO = 'GET_MORE_TVSHOW_INFO';
export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE';
export const FILTER_MOVIE_DATA = "FILTER_MOVIE_DATA";